# Generated by Django 3.2.13 on 2022-05-08 11:33

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered'),
        ),
    ]
