# Generated by Django 3.2.13 on 2022-05-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_page_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
