# Generated by Django 3.2.13 on 2022-05-23 08:04

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220523_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='text_rendered',
        ),
        migrations.AlterField(
            model_name='page',
            name='filename',
            field=models.CharField(max_length=60, unique=b'I01\n', verbose_name='filename'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=martor.models.MartorField(),
        ),
    ]
