# Generated by Django 3.2.13 on 2022-05-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220523_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(verbose_name='Page Content'),
        ),
    ]
