# Generated by Django 3.2.13 on 2022-05-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_page_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(verbose_name='Page Content (MARKDOWN only)'),
        ),
    ]
